#!/bin/bash

# This script installs modules for puppet standalone

echo "[Info] Running pre-puppet.sh for install modules"

if [ "x$(dpkg -l | grep -E '^ii\s+git\s')" == "x" ]
then
    echo "[Info] Installing git"
    apt-get -y install git || (echo "[Error] Cant install git" && exit 0)
else
    echo "[Info] git already is installed, skipping"
fi
sudo apt-get install ruby1.9.1-dev
if [ "x$(gem list librarian-puppet|grep -v LOCAL)" == "x" ]
then
    echo "[Info] Installing librarian-puppet"
    gem install librarian-puppet ||
           (echo "[Error] Cant install librarian-puppet" && exit 0)
else
    echo "[Info] librarian-puppet already is installed, skipping"
fi

if [ ! -e Puppetfile ]
then

    cat > Puppetfile << EOF
#!/usr/bin/env ruby
#^syntax detection

# Warning!
# Do not edit this file, check pre-puppet.sh script!
#

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in Modulefile
#modulefile
 mod 'biemond/wildfly'
 mod 'saz/timezone'
 mod 'saz/locales'
 mod 'puppetlabs/java',
      :git => "https://github.com/puppetlabs/puppetlabs-java.git"
EOF

fi

mkdir -p /opensuse-jb/.vagrant/modules
echo "[Info] Installing puppet modules"
librarian-puppet install --path=/opensuse-jb/.vagrant/modules ||
      (echo "[Error] Cant install modules" && exit)

echo "removing Puppetfile"
rm Puppetfile*


exit 0
